//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenbacks.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementPayee
    {
        public int PayeeId { get; set; }
        public string StatementName { get; set; }
    
        public virtual Payee Payee { get; set; }
    }
}
