//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenbacks.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int PayeeId { get; set; }
        public int CategoryId { get; set; }
        public string CheckNumber { get; set; }
        public bool Clear { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public bool TaxDeductable { get; set; }
        public bool Taxable { get; set; }
        public bool Expense { get; set; }
        public bool Reimbersable { get; set; }
        public string Memo { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
        public virtual Payee Payee { get; set; }
    }
}
